run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - revive
    - staticcheck
    - ineffassign
    - gosimple
    - unused

linters-settings:
  revive:
    rules:
      - name: var-naming
      - name: line-length-limit
        arguments: [120]
